###########################################################################
# Spring Boot's central application configuration file.
#


# application configuration properties
#
application:
  print_bean_info: false      # print information about registered beans


# connection to database (assumed running on localhost, listening on port 3306)
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FREERIDER_DB
    username: freerider
    password: free.ride


# configuration for log output for levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# see: https://howtodoinjava.com/spring-boot2/logging/configure-logging-application-yml
#
logging:
  pattern:
    console: "%msg%n"         # use short format
  level:
    root: INFO               # disable Spring Boot logs
    '[de.freerider]': INFO    # allow application-level INFO logs
    '[org.springframework.jdbc.core]': TRACE  # log SQL statements
    '[org.springframework.web]': TRACE  # log SQL statements
    '[org.apache.tomcat]': INFO
    web: TRACE


# tomcat server port configuration
#
server:
  port : 8080


# springdoc/swagger configuration
#
springdoc:
  writer-with-order-by-keys: true   # keep API order on apidoc-site


# enable to read api docs from static file: api-docs.yaml
#   swagger-ui:
#     url: /api-docs.yaml   # read from file rather than generate
#     enabled: true
#   api-docs:
#     path: /v3/api-docs
#     enabled: true
